# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Yulong Gao's Webpage"
name                     : &name "Yulong Gao"
url                      : https://yulongg.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
repository               : "yulongg.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160


# Site Author
author:
  name             : "Yulong Gao"
  avatar           : "images/Yulong_bio.jpg"
  bio              : "PhD student at KTH"
  location         : "Stockholm"
  googlescholar    : "https://scholar.google.com/citations?hl=zh-CN&user=xBkFTSQAAAAJ"
  email            : "yulongg@kth.se"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  orcid            : "https://orcid.org/0000-0003-2338-5487"



